### PR TITLE
Homework 3

### PR DESCRIPTION
**Pull request by weesom**

### CODE REVIEW

**Comment by B0RlS** [comment]
Read about the downcase method, it will help in 1 task (bring everything under a single template 'error'

**Comment by weesom** [comment]
> Read about the downcase method, it will help in 1 task (bring everything under a single template 'error'

Nah, actually there are no any problems with the first task(yea, I added downcase). But there are some with the third. 
P.S. could you please be more specific on how to submit HW. Which branch should I pr from? master or special branch for current hw?

**Comment by B0RlS** [comment]
Look, in the master you do nothing. In the telegram conversation, I gave a link on how to properly do a pool ricvest updating the data to the latest version. Further ... you enter the homework folder 3 and create a new branch, switch to it and do everything there. Push: git push origin branch_name.
All descriptions are detailed in the document with the homework.

**Comment by weesom** [comment]
> Look, in the master you do nothing. In the telegram conversation, I gave a link on how to properly do a pool ricvest updating the data to the latest version. Further ... you enter the homework folder 3 and create a new branch, switch to it and do everything there. Push: git push origin branch_name.
> All descriptions are detailed in the document with the homework.

I'll do it next time. The problem I had was with second task: I misspelled a regex there.

**Comment by weesom** [comment]
Nope, I also was wrong with the first one. I've just found out that on travis ci I can see which of the test I didn't pass.

**Pull request merged**
